### ISSUE TITLE
evaluation code for real dataset

### ISSUE THREAD

**Issue by yjcaimeow** [microsoft/SpareNet#11]
Hi, @YANG-H @msftgits @dnfclas @zhangmozhe @msftdata,

Table4 in the main paper shows a quantitative comparison on KITTI dataset in terms of consistency,  fidelity, and minimum matching distance(MMD).   Could you please share the code for the evaluation of the real dataset?

What's more, is the MMD * 10000 or *1000 or just not multiply value?

Best,
YIngjie

**Comment by AlphaPav** [comment]
Thank you for the question!
For the KITTI dataset, we follow the evaluation in GRNet repo (https://github.com/hzxie/GRNet)
We used MMD*1000.
