### ISSUE TITLE
GPU memory leakage (CUDA out of memory after 2 epochs)

### ISSUE THREAD

**Issue by orenkatzir** [microsoft/SpareNet#12]
Hi,
Thank you for this repo. 
Unfortunately, I am unable to train this repo for more than ~2 epochs, at the end I keep getting CUDA out of memory.
Tracking the GPU memory consumption a slow and steady increase is visible.
To check it, I have decreased the BATCH_SIZE to 6 while running on 3 RTX-2080 (10.7 g) GPUs, using nvidia docker cuda:10.1-cudnn8-devel-ubuntu18.04 and pytorch 1.8 (cuda 10.1). 
Running code:
```
python train.py --gpu 0,1,2 --workdir /temp_out --model sparenet
```

Have you encountered such a problem? Is some variable history not released?

**Comment by orenkatzir** [comment]
I might have spotted the problem, not sure as I have only briefly examined the code, but it seems that the actual losses (not the value or a detached version) are accumulating for visualization, will report here if this is the problem.

**Comment by orenkatzir** [comment]
It seems that I was right, and I would be happy to get an approval here. 
All the [update operations](https://github.com/microsoft/SpareNet/blob/main/runners/sparenet_runner.py#L55) should take items not Variables.

**Comment by AlphaPav** [comment]
@orenkatzir
It makes full sense to me. Thanks for reporting the issue! We will fix it.
