### ISSUE TITLE
Unable to Reproduce Results

### ISSUE THREAD

**Issue by chekirou** [microsoft/SpareNet#14]
Hi,
Great paper ! I am trying to recreate your results using selected chunks from the ScanNet dataset. I'm unable to reproduce your results using the pretrained sparenet_model for shape categories that were included in the training data. I processed the points as follows : 
```python
diag = points.max(dim=1).values - points.min(dim=1).values # shape :  1 x N x 3
norm = 1 / torch.linalg.norm(diag)
c = points.mean(dim=1)
points = (points - c) * norm
```
it works fine for points from the val or train set from shapenet but not for clouds such as this one : 
![input_chair](https://user-images.githubusercontent.com/24480293/126999028-d6b203a4-5592-429e-88b4-4411ea5e4d1b.PNG)
I sampled ~1000 points, it always gives this kind of reconstruction for the coarse point cloud: 
![Capture_res_chair](https://user-images.githubusercontent.com/24480293/126999257-0f58dcca-4c0a-4c7a-a044-623f516aa0f2.PNG)
Is there some preprocessing step I'm missing ?
Thank you in advance.

**Comment by AlphaPav** [comment]
Thanks for the question! We haven't incorporated the ScanNet dataset. You can refer to the dataloader of ShapeNet and adapt it for ScanNet:  https://github.com/microsoft/SpareNet/blob/8bbc200f25a3c9e5e9e4d03b685f9c5c655ef071/datasets/data_loaders.py#L145
