### ISSUE TITLE
Depth Maps cannot Supervise Training

### ISSUE THREAD

**Issue by Wi-sc** [microsoft/SpareNet#15]
Hi, thanks for your released code. I'm interested in the your methods that training with depth map. I tried to train an auto-encoder network, where the encoder and decoder are both pointnet. The input and output are point cloud. If I train the network with chamfer distance, it works well. But if I replace the loss function with L1 distance between depth maps, it cannot work. Do you have any suggestions?

**Comment by YANG-H** [comment]
Hi, please check my answer in this issue [here](https://github.com/microsoft/SpareNet/issues/13#issuecomment-890515438).

**Comment by AlphaPav** [comment]
Hi! I assume the issue was resolved, so I am closing the issue. Feel free to reopen if you still have questions.
Thanks.
