### ISSUE TITLE
Batch Time is very slow (around 4 sec) with 4 GPUs (1080ti)

### ISSUE THREAD

**Issue by coreqode** [microsoft/SpareNet#19]
<img width="969" alt="image" src="https://user-images.githubusercontent.com/18486587/134151555-78326aaf-4244-4df0-8ff8-19233a76f5f8.png">

<img width="812" alt="image" src="https://user-images.githubusercontent.com/18486587/134151744-96260654-15ea-4def-88dc-46d75741038c.png">

BatchTime is very slow. I am using batch size of 12 as of now.

**Comment by Chuxwa** [comment]
We use 4 Tesla V100 GPUs to train our model. With the batch size 32, it takes an average of 1.2 seconds to finish one batch. During the training, we need to calculate EMD loss and also render depth map, so the training process can be time-consuming. 

> <img alt="image" width="969" src="https://user-images.githubusercontent.com/18486587/134151555-78326aaf-4244-4df0-8ff8-19233a76f5f8.png">
> 
> <img alt="image" width="812" src="https://user-images.githubusercontent.com/18486587/134151744-96260654-15ea-4def-88dc-46d75741038c.png">
> 
> BatchTime is very slow. I am using batch size of 12 as of now.

We use 4 Tesla V100 GPUs to train our model. With the batch size 32, it takes an average of 1.2 seconds to finish one batch. During the training, we need to calculate EMD loss and also render depth map, so the training process can be time-consuming.

**Comment by Chuxwa** [comment]
We use 4 Tesla V100 GPUs to train our model. With the batch size 32, it takes an average of 1.2 seconds to finish one batch. During the training, we need to calculate EMD loss and also render depth map, so the training process can be time-consuming.
