### ISSUE TITLE
RuntimeError: Expected all tensors to be on the same device, but found at least two devices

### ISSUE THREAD

**Issue by Francisco-liu** [microsoft/SpareNet#5]
Thank you for sharing. Following the instructions strictly， I run trian.py, an error occurred during evaluation after training for an epoch, report as follow:

INFO: - [Epoch 1/150][Batch 1205/1207] BatchTime = 4.602 (s) Losses = ['39.1348', '37.8132']
INFO: - [Epoch 1/150][Batch 1206/1207] BatchTime = 4.770 (s) Losses = ['38.2816', '36.3361']
INFO: - [Epoch 1/150][Batch 1207/1207] BatchTime = 4.825 (s) Losses = ['35.4861', '34.3442']
INFO: - [Epoch 1/150] EpochTime = 6249.984 (s) Losses = ['50.3621', '49.7149']
INFO: - Start validating.
Traceback (most recent call last):
  File "train.py", line 79, in <module>
    main()
  File "train.py", line 75, in main
    model.runner()
  File "/home/cvlab/lxz/sparenet/runners/base_runner.py", line 338, in runner
    self.val()
  File "/home/cvlab/lxz/sparenet/runners/base_runner.py", line 209, in val
    self.val_step(items)
  File "/home/cvlab/lxz/sparenet/runners/sparenet_runner.py", line 63, in val_step
    _, refine_ptcloud, _, _, refine_loss, coarse_loss = self.completion(data)
  File "/home/cvlab/lxz/sparenet/runners/sparenet_runner.py", line 102, in completion
    _loss = coarse_loss + middle_loss + refine_loss + expansion_penalty.mean() * 0.1
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:4!

Could you please provide some suggestions about this？

**Comment by AlphaPav** [comment]
Hi, @Francisco-liu, thanks for reporting the issue. 

What is the specific command you are running (--gpu, etc )?

**Comment by Francisco-liu** [comment]
Hi, @AlphaPav , thanks for your reply. I use
python  train.py --gpu 4,5,6,7 --model sparenet

**Comment by AlphaPav** [comment]
Hi @Francisco-liu 
This bug is fixed in our current version. Thanks again!

**Comment by Francisco-liu** [comment]
Thanks！

**Comment by Francisco-liu** [comment]
good
