### ISSUE TITLE
 CPU memory consumption is too large

### ISSUE THREAD

**Issue by Francisco-liu** [microsoft/SpareNet#6]
Hello, sorry to disturb you again.I used your code to train for 3 epochs, and the cpu memory consumption reached 40G. The memory will continue to increase as the number of training increases. Eventually, the memory overflow will cause the program to terminate. I don't know why the memory consumption is so high, can you give me some suggestions? In your experiment, how much CPU memory does it take up to 150 epochs after training?

**Comment by AlphaPav** [comment]
@Francisco-liu Sorry for the late reply. It may be because of this issue: https://github.com/microsoft/SpareNet/issues/12#issuecomment-888030036 
The code is updated.
