### ISSUE TITLE
Unable to training

### ISSUE THREAD

**Issue by 17353303313** [microsoft/SpareNet#9]
input
python  train.py --gpu 0 --workdir ./output/logs/ --model sparenet --weights ./output/logs/checkpoints
The results are as follows（Partly as a result）
INFO: - Collecting files of Taxonomy [ID=04256520, Name=sofa]                                                                                                                                                                                                     
INFO: - Collecting files of Taxonomy [ID=04379243, Name=table]                                                                                                                                                                                                    
INFO: - Collecting files of Taxonomy [ID=04530566, Name=watercraft]                                                                                                                                                                                               
INFO: - Complete collecting files of the dataset. Total files: 231792                                                                                                                                                                                             
INFO: - Collecting files of Taxonomy [ID=02691156, Name=airplane]
INFO: - Collecting files of Taxonomy [ID=02933112, Name=cabinet]                                                                                                                                                                                                  
INFO: - Collecting files of Taxonomy [ID=02958343, Name=car]                                                                                                                                                                                                      
INFO: - Collecting files of Taxonomy [ID=03001627, Name=chair]                                                                                                                                                                                                    
INFO: - Collecting files of Taxonomy [ID=03636649, Name=lamp]                                                                                                                                                                                                     
INFO: - Collecting files of Taxonomy [ID=04256520, Name=sofa]                                                                                                                                                                                                     
INFO: - Collecting files of Taxonomy [ID=04379243, Name=table]                                                                                                                                                                                                    
INFO: - Collecting files of Taxonomy [ID=04530566, Name=watercraft]                                                                                                                                                                                               
INFO: - Complete collecting files of the dataset. Total files: 1200                                                                                                                                                                                               
DEBUG: - update config NUM_CLASSES: 8.
INFO: - Finish building dataset.
Residualnet
generating 2D grid
DEBUG: - Parameters in net_G: 82562191.
INFO: - Recovering from ./output/logs/checkpoints ...
INFO: - Recover complete. Current epoch = #150; best metrics = {'F-Score': 0.6606881591485739, 'ChamferDistance': 0.5150378787751227, 'EMD': 1.8626600753050297}.
INFO: - runner time: 0.000025
(Sparenet) medialab@medialab-7910:~/workspace/YZQ/SpareNetNew$ python  train.py --gpu 0 --workdir ./output/logs/ --model sparenet --weights ./output/logs/checkpoints

Please give advice or commentsThere is no training process

**Comment by AlphaPav** [comment]
Does your checkpoint model already train 150 epochs? 
If the max epoch `n_epochs` is also 150, there will be no training process.

**Comment by 17353303313** [comment]
I think I changed the code to only output training 150
1. In utils\misc.py
the code changes as follows
 #checkpoint = torch.load(cfg.CONST.weights)      The code is modified to load  model as follows ,and test.py This code works fine
 checkpoint = torch.load("/home/medialab/workspace/YZQ/SpareNetNew/models/SpareNet.pth")
but train.py no training process,the code is not working properly
DEBUG: - Parameters in net_G: 82562191.
INFO: - Recovering from ./output/logs/checkpoints ...
INFO: - Recover complete. Current epoch = #150; best metrics = {'F-Score': 0.6606881591485739, 'ChamferDistance': 0.5150378787751227, 'EMD': 1.8626600753050297}.
INFO: - runner time: 0.000025
2.checkpoint = torch.load(cfg.CONST.weights)  Not modify this line of code，
2.1 python  test.py --gpu 0 --workdir ./output/ --model sparenet --weights ./output/checkpoints/ --test_mode default
The results are as follows
INFO: - Complete collecting files of the dataset. Total files: 1200                                                                                                                                                         
DEBUG: - update config NUM_CLASSES: 8.
INFO: - Finish building dataset.
Residualnet
generating 2D grid
DEBUG: - Parameters in net_G: 82562191.
INFO: - Recovering from ./output/checkpoints/ ...
cfffffffffffffffg ./output/checkpoints/
<class 'str'>
Traceback (most recent call last):
  File "test.py", line 81, in <module>
    main()
  File "test.py", line 75, in main
    model = getattr(module, args.model + "Runner")(cfg, logger)
  File "/home/medialab/workspace/YZQ/SpareNetNew/runners/sparenet_runner.py", line 19, in __init__
    super().__init__(config, logger)
  File "/home/medialab/workspace/YZQ/SpareNetNew/runners/base_runner.py", line 79, in __init__
    self.models_load()
  File "/home/medialab/workspace/YZQ/SpareNetNew/runners/base_runner.py", line 108, in models_load
    self.init_epoch, self.best_metrics = um.model_load(self.config, self.models)
  File "/home/medialab/workspace/YZQ/SpareNetNew/utils/misc.py", line 74, in model_load
    checkpoint = torch.load(cfg.CONST.weights)
  File "/home/medialab/anaconda3/envs/Sparenet/lib/python3.7/site-packages/torch/serialization.py", line 579, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/medialab/anaconda3/envs/Sparenet/lib/python3.7/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/medialab/anaconda3/envs/Sparenet/lib/python3.7/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
IsADirectoryError: [Errno 21] Is a directory: './output/checkpoints/'
2.2 python  train.py --gpu 0 --workdir ./output/ --model sparenet --weights ./output/checkpoints/
The results are as follows
INFO: - Finish building dataset.
Residualnet
generating 2D grid
DEBUG: - Parameters in net_G: 82562191.
INFO: - Recovering from ./output/checkpoints/ ...
cfffffffffffffffg ./output/checkpoints/
<class 'str'>
Traceback (most recent call last):
  File "train.py", line 74, in <module>
    main()
  File "train.py", line 66, in main
    model = getattr(module, args.model + "Runner")(cfg, logger)
  File "/home/medialab/workspace/YZQ/SpareNetNew/runners/sparenet_runner.py", line 19, in __init__
    super().__init__(config, logger)
  File "/home/medialab/workspace/YZQ/SpareNetNew/runners/base_runner.py", line 79, in __init__
    self.models_load()
  File "/home/medialab/workspace/YZQ/SpareNetNew/runners/base_runner.py", line 108, in models_load
    self.init_epoch, self.best_metrics = um.model_load(self.config, self.models)
  File "/home/medialab/workspace/YZQ/SpareNetNew/utils/misc.py", line 74, in model_load
    checkpoint = torch.load(cfg.CONST.weights)
  File "/home/medialab/anaconda3/envs/Sparenet/lib/python3.7/site-packages/torch/serialization.py", line 579, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/medialab/anaconda3/envs/Sparenet/lib/python3.7/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/medialab/anaconda3/envs/Sparenet/lib/python3.7/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
IsADirectoryError: [Errno 21] Is a directory: './output/checkpoints/'

I want to retrain. What should I do，thanks

**Comment by AlphaPav** [comment]
Hi, as shown in the error, ‘ ./output/checkpoints/’ is a directory, not a file of the pre-trained model. If you don't want to use any pre-trained model,  the argument `--weights` doesn't need to be specified. 

If you want to train from scratch, you can run: 
`python  train.py --gpu 0,1,2,3 --work_dir ./output/ --model sparenet`
